// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication5.DAL;

#nullable disable

namespace WebApplication5.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20250622155301_Tabel")]
    partial class Tabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication5.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "John",
                            HireDate = new DateOnly(2020, 1, 15),
                            LastName = "Doe"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Jokky",
                            HireDate = new DateOnly(2020, 2, 15),
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("WebApplication5.Models.Nursery", b =>
                {
                    b.Property<int>("NurseryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NurseryId"));

                    b.Property<DateOnly>("EstablishedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NurseryId");

                    b.ToTable("Nurseries");

                    b.HasData(
                        new
                        {
                            NurseryId = 1,
                            EstablishedDate = new DateOnly(2015, 3, 10),
                            Name = "Green Haven"
                        },
                        new
                        {
                            NurseryId = 2,
                            EstablishedDate = new DateOnly(2015, 8, 10),
                            Name = "Haven"
                        });
                });

            modelBuilder.Entity("WebApplication5.Models.Responsible", b =>
                {
                    b.Property<int>("Employee")
                        .HasColumnType("integer");

                    b.Property<int>("BatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Employee", "BatchId");

                    b.ToTable("Responsibles");

                    b.HasData(
                        new
                        {
                            Employee = 1,
                            BatchId = 1,
                            Role = "Manager"
                        },
                        new
                        {
                            Employee = 2,
                            BatchId = 2,
                            Role = "Supervisor"
                        });
                });

            modelBuilder.Entity("WebApplication5.Models.SeedlingBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchId"));

                    b.Property<int>("NurseryId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReadyDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SowndDate")
                        .HasColumnType("date");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("BatchId");

                    b.ToTable("Seedling_Batch");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            NurseryId = 1,
                            Quantity = 1000,
                            ReadyDate = new DateOnly(2023, 6, 1),
                            SowndDate = new DateOnly(2023, 1, 1),
                            SpeciesId = 1
                        },
                        new
                        {
                            BatchId = 2,
                            NurseryId = 2,
                            Quantity = 700,
                            ReadyDate = new DateOnly(2023, 9, 1),
                            SowndDate = new DateOnly(2023, 5, 1),
                            SpeciesId = 2
                        });
                });

            modelBuilder.Entity("WebApplication5.Models.TreeSpecies", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpeciesId"));

                    b.Property<int>("GrowthTimeInYears")
                        .HasColumnType("integer");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SpeciesId");

                    b.ToTable("Tree_Species");

                    b.HasData(
                        new
                        {
                            SpeciesId = 1,
                            GrowthTimeInYears = 1,
                            LatinName = "Oak"
                        },
                        new
                        {
                            SpeciesId = 2,
                            GrowthTimeInYears = 2,
                            LatinName = "Burak"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
